version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    image: "${IMAGE_NAME}:${TAG_NAME}"
    environment:
      NODE_ENV: development
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - "3000:3000"
