version: '2'
services:
  web:
    build: .
    env_file:
      - .env
    image: "${IMAGE_NAME}:${TAG_NAME}"
    environment:
      NODE_ENV: development
    ports:
      - ${TARGET_PORT}:${HOST_PORT}
