version: '2'
services:
  web:
    build: .
    env_file:
      - .env
    image: "${IMAGE_NAME}:${TAG_NAME}"
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
