version: '3'
services:
  web:
    build: .
    command: npm run dev
    env_file:
      - .env
    image: "${IMAGE_NAME}:${TAG_NAME}"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
