name: Docker Image CI Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Github Docker Registry
      run: echo ${GITHUB_TOKEN} | docker login -u ${DOCKER_USERNAME} --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker-compose up
    - name: Push the latest Docker image
      run: docker-compose push
