name: Docker Image CI Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Git Docker Registry
      run: cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u ${{ secrets.Git_Docker_Usename }} --password-stdin
    - name: Build the Docker image
      run: docker-compose up
    - name: Push the latest Docker image
      run: docker-compose push
