name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t munishsinghal/aseapi:latest -f ./Dockerfile.yaml .
    - name: Push the latest Docker image
      run: docker push munishsinghal/aseapi:latest

