name: Docker Image CI Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Git Docker Registry
      with:
        name: Login to Git Docker Registry1
        username: ${{ github.Git_Docker_Usename }}
        password: ${{ secrets.Github_Docker_Token }}
        registry: docker.pkg.github.com
       
    - name: Build the Docker image
      run: docker-compose up
    - name: Push the latest Docker image
      run: docker-compose push
