name: Run ESLint on Pull Requests

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 18F/github-action-eslint@1.0.0
        with:
          repo-token: ${{ secrets.GIT_TOKEN }}
          files: src/
          path: web/