name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker-compose up
    - name: Push the latest Docker image
      run: docker-compose push

    - uses: actions/checkout@v1
    - uses: hallee/eslint-action@master
      with:
        repo-token: ${{secrets.CODEQUALITY_TOKEN}}