name: Docker Image CI Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: docker-compose up
    - name: Push the latest Docker image
      run: docker-compose push
